---
title: "Problems with delta(log(cumulative))"
output: html_notebook
---

```{r}
# This class represents and Non-pharmacological intervention.
# The NPI is in place from day |start| to day |end| inclusive.
setClass("npi",
         slots = list(
           start = "numeric",
           end = "numeric",
           factor = "numeric"
         ))
# Convenient constructor for NPIs.
NPI <-
  function(start, end, factor)
    new("npi",
        start = start,
        end = end,
        factor = factor)

# Returns true if a day is impacted by |npi|
in_npi <- function(npi, i) {
  i >= npi@start && i <= npi@end
}

# Returns the last day impacted by any NPI in |npis|
npis_end <- function(npis) {
  max(sapply(npis, function(x) {
    x@end
  }))
}

# A vector of 0/1 for each day simulated. A day gets a 1 if the NPI is active on that day, 0 otherwise.
# Used as a predictor in the linear regression.
npi_pred <- function(npis, i) {
  last <- npis_end(npis)
  npi = npis[[i]]
  pred <- numeric()
  value = 0
  for (d in 1:last) {
    pred <- append(pred, (if (in_npi(npi, d))
      1
      else
        0))
  }
  pred
}

# Scales a growth rate so that it becomes |rate| every |period| days.
scale <- function(rate, period) {
  exp(log(rate) / period)
}

# Returns a vector of growth rates by combining |npis| with a base growth rate.
# All growth is scaled over |period| days.
createGrowthRates <- function(base_rate, npis, period) {
  last <- npis_end(npis)
  rates <- numeric()
  for (i in 1:last) {
    rate <- scale(base_rate, period)
    for (npi in npis) {
      if (in_npi(npi, i)) {
        rate <- rate * scale(npi@factor, period)
      }
    }
    rates <- append(rates, rate)
  }
  rates
}

# Create a timeseries of cases based on the supplied vector of daily growth rates.
createCases <- function(rates) {
  cases <- c(1)
  for (rate in rates) {
    cases <- append(cases, tail(cases, 1) * rate)
  }
  cases
}

# Returns the coefficients for the impact of |npis| by applying linear regression to diff(log(|cases|)).
regress <- function(npis, cases) {
  d_l = diff(log(cases))
  npi1 <- npi_pred(npis, 1)
  npi2 <- npi_pred(npis, 2)
  d = data.frame(y = d_l,
                 npi1 = npi1,
                 npi2 = npi2)
  r.model <- lm(y ~ npi1 + npi2, data = d)
  r.model$coefficients
}

# Dump out some info on the coefficients.
renderRates <- function(c, period) {
  print("coefficients")
  print(c)
  cat("coefficients as rates per ", period, " days\n")
  print(exp(c * period))
  print("npi2 - npi1")
  print(c["npi2"] - c["npi1"])
}

regressAndRender <- function(npis, cases, period) {
  c <- regress(npis, cases)
  renderRates(c, period)
}

# Apply the methodology to |npis| with a base growth rate of |r0|.
# Scale all rates to be per |period|
doOne <- function(npis, r0, period) {
  rates <- createGrowthRates(1.5, npis, period)
  
  daily = createCases(rates)
  cumulative = cumsum(daily)
  
  plot(cases, ylab="daily cases")
  plot(cumulative, ylab="cumulative cases")
  
  d_l_daily <- diff(log(daily))
  d_l_cumulative <- diff(log(cumulative))
  
  plot(d_l_daily,ylab="delta(log(daily cases))")
  plot(d_l_cumulative, ylab="delta(log(cumulative cases))")
  
  regressAndRender(npis, daily, period)
  regressAndRender(npis, cumulative, period)
}

npis <- c(NPI(11, 30, 0.6), NPI(21, 30, 0.6))
doOne(npis, 2.5, 7)
```

```{r}
npis <- c(NPI(11, 30, .8), NPI(21, 30, .4))
doOne(npis, 2.5, 7)
```
